version: "3"

services:
  garmin-to-nextcloud:
    build: .
    environment:
      GARMIN_EMAILS: "email1@example.com;email2@example.com"
      GARMIN_PASSWORDS: "pass1;pass2"
      NEXTCLOUD_USER_PATHS : "path/1;path/2"
    restart: unless-stopped
